#    Licensed to the Apache Software Foundation (ASF) under one or more
#    contributor license agreements.  See the NOTICE file distributed with
#    this work for additional information regarding copyright ownership.
#    The ASF licenses this file to You under the Apache License, Version 2.0
#    (the "License"); you may not use this file except in compliance with
#    the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

version: "3.8"
volumes:
  zookeeper:
  nifi_conf:
  nifi_db:
  nifi_content:
  nifi_flowfile:
  nifi_logs:
  nifi_provenance:
  nifi_state:

networks:
  nifi:
    name: nifi

services:
  service:
    hostname: nifi-0
    image: apache/nifi:1.13.2
    ports:
      - 9090:8080 # Unsecured HTTP Web Port
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    networks:
      - nifi
    volumes:
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_db:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi_logs:/opt/nifi/nifi-current/logs
      - ./nifi-7zip-nar/target:/opt/nifi/nifi-current/extensions
